apiVersion: v1
kind: Service
metadata:
  name: api-hackaton-svc
  annotations:
    alb.ingress.kubernetes.io/security-groups: eks_default
spec:
  type: LoadBalancer
  selector:
    app: api-hackaton
  ports:
    - port: 3000
      targetPort: 3000
